name: Dependency Update

on:
  schedule:
    # Runs every Sunday at 3:00 PM IST (09:30 UTC)
    - cron: '30 9 * * 0'
  workflow_dispatch: # allows manual trigger

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry

      - name: Update dependencies
        run: |
          poetry update

      - name: Commit updated poetry.lock
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add poetry.lock
          git commit -m "chore: update dependencies [skip ci]" || echo "No changes to commit"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          branch: dependency-update
          title: "chore: update dependencies"
          body: "This PR updates Python dependencies using Poetry."
          base: master
